name: Playwright Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build Strapi app
        run: pnpm build

      - name: Start Strapi app and log output
        run: pnpm start > strapi.log 2>&1 &
        env:
          NODE_ENV: production
          PORT: 1337
          APP_KEYS: ${{ secrets.APP_KEYS }}
          API_TOKEN_SALT: ${{ secrets.API_TOKEN_SALT }}
          ADMIN_JWT_SECRET: ${{ secrets.ADMIN_JWT_SECRET }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - name: Wait for Strapi to be ready
        run: |
          echo "Waiting for Strapi to start..."
          pnpm add wait-on --global # Install wait-on tool
          wait-on tcp:1337 -t 30000 # Increased timeout to 30 seconds
          echo "Strapi is ready!"
        continue-on-error: true

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/
